---
- hosts: localhost
  connection: local
  become: true
  tasks:

  - name: update all packages
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_facts["distribution"] == "Ubuntu"

  - name: install apache
    ansible.builtin.apt:
      name: apache2
      status: latest
    when: ansible_facts["distribution"] == "Ubuntu"
